use_frameworks!

platform :ios, '17.0'

target 'HorizontalPageControl_Example' do
  pod 'HorizontalPageControl', :path => '../'

  target 'HorizontalPageControl_Tests' do
    inherit! :search_paths

    
  end
end
